### ISSUE TITLE
Problem in `__init__`.

### ISSUE THREAD

**Issue by RohanKarthikeyan** [RohanKarthikeyan/OneCar#2]
https://github.com/RohanKarthikeyan/OneCar/blob/03fd2743c5796a863d9e065edfbe8c3af2ab08ac/2cars_manual.py#L118-L119

The lengths of these lists should depend on the value of `self.n_cars`.

**Comment by saranggalada** [comment]
Ah right. I had quickly made this modification then that's why just kept it as two

**Comment by RohanKarthikeyan** [comment]
Please make the changes in the `reset()` function also.

**Comment by saranggalada** [comment]
done
